unique_ids:
  assets:
    standard-page.html: E66QH75WXGLTKFVHTQRBEV76V2HH3BAN
    theme.css: XGSEOZXIQCZZD3YQ232LDEAPP4N3A56P
  forms:
    Form1: VHUIWH2COZBDCAGK6BC32DT3J7IDDQDF
  modules: {}
  scripts: {}
  server_modules: {}
